# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f931be8f4046d68c59c4ae168559f20ff612a2eb662acb293124acbadcaedb3c81fbf0a0911bf423c15f9260a28487c486c8c893c8c7a79e45cedc54da2961c9

test:
  secret_key_base: 8ffb50cd457f7b5a30002f54e07e26d5c44b26611bcbc805313ff774e390f85d9ed1cdbab911231d777d55080296da3cb0352fad0ec388b5bba724e5b5f2d0c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
